ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

#-   repo: https://github.com/codespell-project/codespell
#    rev: v2.2.6
#    hooks:
#    -   id: codespell
#        args:
#        -   --skip=*.ts,*.svg,*.hqx
#        -   --ignore-words=.codespell_ignore_words.txt

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args:
        -   --py36-plus
