ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: fix-byte-order-marker
    #- id: clang-format
    #    args:
    #    -   --style=Google
    #-   id: clang-tidy
    #-   id: oclint
    #-   id: uncrustify
    #-   id: cppcheck
    #-   id: cpplint
    #-   id: include-what-you-use

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        args:
        -   --skip=*.ts,*.svg,*.hqx,*-inv.txt,*.iss.in
        -   --ignore-words=.codespell_ignore_words.txt
        #-   --ignore-words-list="SEH,Ot,inOut,MARGE,Manuel"

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args:
        -   --py36-plus
