exclude: ^(gtest-1.12.1)/

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --skip=*.ts,*.svg,*.hqx,*-inv.txt,*.iss.in
          - --ignore-words=.codespell_ignore_words.txt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.2
    hooks:
      - id: pylint
        files: .*\.py$
        args: [
          "--max-line-length=120",
          "--disable=C0103,
          C0112,
          C0114,
          C0117,
          C0121,
          C0123,
          C0200,
          C0201,
          C0205,
          C0206,
          C0207,
          C0209,
          C0301,
          C0302,
          C0303,
          C0325,
          C0410,
          C0411,
          C0412,
          C0413,
          C0414,
          C0415,
          C1802,
          C1803,
          C3001,
          E0001,
          E0102,
          E0118,
          E0203,
          E0213,
          E0306,
          E0401,
          E0601,
          E0602,
          E0606,
          E0611,
          E0702,
          E0704,
          E1101,
          E1120,
          E1126,
          E1136,
          R0124,
          R0402,
          R0902,
          R0903,
          R0904,
          R0911,
          R0912,
          R0913,
          R0914,
          R0915,
          R0916,
          R0917,
          R1701,
          R1702,
          R1703,
          R1704,
          R1705,
          R1706,
          R1710,
          R1711,
          R1714,
          R1716,
          R1720,
          R1721,
          R1723,
          R1724,
          R1728,
          R1729,
          R1732,
          R1735,
          W0101,
          W0102,
          W0104,
          W0105,
          W0106,
          W0107,
          W0109,
          W0122,
          W0123,
          W0125,
          W0201,
          W0212,
          W0221,
          W0222,
          W0223,
          W0231,
          W0237,
          W0238,
          W0401,
          W0404,
          W0511,
          W0601,
          W0602,
          W0603,
          W0604,
          W0611,
          W0612,
          W0613,
          W0614,
          W0621,
          W0622,
          W0632,
          W0641,
          W0702,
          W0707,
          W0718,
          W1308,
          W1514,
          W3301,
          W4901",
          "--py-version=3.7"
        ]

#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.45.0  # Use the latest version of Ruff
#    hooks:
#      - id: ruff
#        args: [--fix]  # Optional: Automatically fix linting issues
#        additional_dependencies:  # Optional: Add extra dependencies if needed
#         - ruff[flake8]  # Example: Enables Flake8 compatibility

#  - repo: https://github.com/pre-commit/mirrors-clang-format
#    rev: v15.0.7
#    hooks:
#      - id: clang-format
#        args: [-style=file]
